/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'id' : CardID,
  'csvColumnMapping' : CsvColumnMapping,
  'name' : string,
  'categoryMappings' : Array<CategoryMapping>,
}
export type CardID = string;
export interface CategoryMapping {
  'cardProvidedCategory' : string,
  'customCategoryID' : CustomCategoryID,
}
export type CategoryType = { 'need' : null } |
  { 'want' : null };
export interface CsvColumnMapping {
  'categoryColumn' : bigint,
  'dateColumn' : bigint,
  'descriptionColumn' : bigint,
  'amountColumn' : bigint,
}
export interface CustomCategory {
  'id' : CustomCategoryID,
  'categoryType' : CategoryType,
  'name' : string,
}
export type CustomCategoryID = string;
export interface Transaction {
  'categoryID' : CustomCategoryID,
  'date' : string,
  'description' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<[CardID, string, CsvColumnMapping], boolean>,
  'addCategoryMapping' : ActorMethod<[CardID, CategoryMapping], undefined>,
  'addCustomCategory' : ActorMethod<
    [CustomCategoryID, string, CategoryType],
    boolean
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCards' : ActorMethod<[], Array<Card>>,
  'getCustomCategories' : ActorMethod<[], Array<CustomCategory>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processImportedTransactions' : ActorMethod<
    [CardID, Array<Transaction>],
    undefined
  >,
  'resetTransactions' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomCategoryType' : ActorMethod<
    [CustomCategoryID, CategoryType],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];