/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardID = IDL.Text;
export const CsvColumnMapping = IDL.Record({
  'categoryColumn' : IDL.Nat,
  'dateColumn' : IDL.Nat,
  'descriptionColumn' : IDL.Nat,
  'amountColumn' : IDL.Nat,
});
export const CustomCategoryID = IDL.Text;
export const CategoryMapping = IDL.Record({
  'cardProvidedCategory' : IDL.Text,
  'customCategoryID' : CustomCategoryID,
});
export const CategoryType = IDL.Variant({
  'need' : IDL.Null,
  'want' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Card = IDL.Record({
  'id' : CardID,
  'csvColumnMapping' : CsvColumnMapping,
  'name' : IDL.Text,
  'categoryMappings' : IDL.Vec(CategoryMapping),
});
export const CustomCategory = IDL.Record({
  'id' : CustomCategoryID,
  'categoryType' : CategoryType,
  'name' : IDL.Text,
});
export const Transaction = IDL.Record({
  'categoryID' : CustomCategoryID,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func([CardID, IDL.Text, CsvColumnMapping], [IDL.Bool], []),
  'addCategoryMapping' : IDL.Func([CardID, CategoryMapping], [], []),
  'addCustomCategory' : IDL.Func(
      [CustomCategoryID, IDL.Text, CategoryType],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getCustomCategories' : IDL.Func([], [IDL.Vec(CustomCategory)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processImportedTransactions' : IDL.Func(
      [CardID, IDL.Vec(Transaction)],
      [],
      [],
    ),
  'resetTransactions' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomCategoryType' : IDL.Func(
      [CustomCategoryID, CategoryType],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardID = IDL.Text;
  const CsvColumnMapping = IDL.Record({
    'categoryColumn' : IDL.Nat,
    'dateColumn' : IDL.Nat,
    'descriptionColumn' : IDL.Nat,
    'amountColumn' : IDL.Nat,
  });
  const CustomCategoryID = IDL.Text;
  const CategoryMapping = IDL.Record({
    'cardProvidedCategory' : IDL.Text,
    'customCategoryID' : CustomCategoryID,
  });
  const CategoryType = IDL.Variant({ 'need' : IDL.Null, 'want' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Card = IDL.Record({
    'id' : CardID,
    'csvColumnMapping' : CsvColumnMapping,
    'name' : IDL.Text,
    'categoryMappings' : IDL.Vec(CategoryMapping),
  });
  const CustomCategory = IDL.Record({
    'id' : CustomCategoryID,
    'categoryType' : CategoryType,
    'name' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'categoryID' : CustomCategoryID,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func([CardID, IDL.Text, CsvColumnMapping], [IDL.Bool], []),
    'addCategoryMapping' : IDL.Func([CardID, CategoryMapping], [], []),
    'addCustomCategory' : IDL.Func(
        [CustomCategoryID, IDL.Text, CategoryType],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getCustomCategories' : IDL.Func([], [IDL.Vec(CustomCategory)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processImportedTransactions' : IDL.Func(
        [CardID, IDL.Vec(Transaction)],
        [],
        [],
      ),
    'resetTransactions' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomCategoryType' : IDL.Func(
        [CustomCategoryID, CategoryType],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };